In [1]:
import numpy as np

In [2]:
benimdizim = np.arange(0,15)

In [3]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimdizim[5]

5

In [6]:
benimdizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimdizim[3:8] = -5

In [8]:
benimdizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskadizi = np.arange(0,24)

In [10]:
baskadizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
baskadizi[4:9]

array([4, 5, 6, 7, 8])

In [12]:
slicingdizisi = baskadizi[4:9]

In [13]:
slicingdizisi

array([4, 5, 6, 7, 8])

In [14]:
slicingdizisi = 700

In [15]:
slicingdizisi

700

In [16]:
type(slicingdizisi)

int

In [17]:
slicingdizisi = baskadizi[4:9]

In [18]:
slicingdizisi

array([4, 5, 6, 7, 8])

In [19]:
slicingdizisi[:] = 700

In [20]:
slicingdizisi

array([700, 700, 700, 700, 700])

In [21]:
baskadizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [22]:
ornekdizi = np.arange(0,24)

In [23]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
ornekdizikopyasi  = ornekdizi.copy()

In [25]:
ornekdizikopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
ornekdizikopyasiSlicing = ornekdizikopyasi[3:6]

In [27]:
ornekdizikopyasiSlicing[:] = 800

In [28]:
ornekdizikopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
#gördüğün gibi değişmedi. copy() fonksiyonunu kullan

# matrix

In [32]:
benimListem = [[10,20,30], [20,30,40],[40,50,60]]

In [33]:
benimMatrixDizim = np.array(benimListem)

In [34]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [35]:
benimMatrixDizim[0]

array([10, 20, 30])

In [36]:
benimMatrixDizim[1][2]

40

In [37]:
benimMatrixDizim[1,2]

40

In [38]:
benimMatrixDizim[1:,2]
#birinci row dan itibaren al, ama ikinci indexleri

array([40, 60])

In [40]:
benimMatrixDizim[1:,1:]

array([[30, 40],
       [50, 60]])

In [41]:
benimMatrixDizim[2:,2:]

array([[60]])

In [43]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [45]:
yeniMatrix = np.array(yeniListe)

In [46]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
yeniMatrix[[4,2,0]]
# 4 2 ve 0. indexleri alarak bas

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

# operasyonlar

In [51]:
yenibirDizi = np.random.randint(1,100,20)

In [52]:
yenibirDizi

array([55, 52, 23, 16, 52, 57, 44, 59,  1, 46, 76, 44, 48, 60, 63, 70, 57,
       79, 78, 24])

In [53]:
yenibirDizi > 24

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [54]:
yenibirDizi

array([55, 52, 23, 16, 52, 57, 44, 59,  1, 46, 76, 44, 48, 60, 63, 70, 57,
       79, 78, 24])

In [55]:
sonucDizisi = yenibirDizi > 24

In [56]:
sonucDizisi

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False])

In [58]:
yenibirDizi[sonucDizisi]

array([55, 52, 52, 57, 44, 59, 46, 76, 44, 48, 60, 63, 70, 57, 79, 78])

In [59]:
sonDizi = np.arange(0,24)

In [60]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [62]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [63]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [64]:
sonDizi / sonDizi

C:\Users\omer\AppData\Local\Temp\ipykernel_14988\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [67]:
np.max(sonDizi)

23

In [68]:
np.min(sonDizi)

0