In [1]:
import numpy as np

In [2]:
listem = [1,2,3,4,5]

In [3]:
type(listem)

list

In [4]:
np.array(listem)

array([1, 2, 3, 4, 5])

In [5]:
type(np.array(listem))

numpy.ndarray

In [6]:
matrixlistesi = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
matrixlistesi[0]

[1, 2, 3]

In [8]:
matrixlistesi[0][2]

3

In [9]:
np.array(matrixlistesi)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [10]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

# zeros

In [13]:
 np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((5,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [16]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [17]:
np.linspace(0,20,6)
# 0 dan 20 ye kadar 6 sayı yazdır. aralarındaki boşluk miktarı aynı olsun

array([ 0.,  4.,  8., 12., 16., 20.])

# eye

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random

In [19]:
np.random.randn(5)

array([ 0.2506531 ,  0.2067342 , -1.17227376,  0.09047896, -0.35089841])

In [20]:
np.random.randn(4,4)

array([[ 0.96583897,  0.98454172,  0.55576385, -0.75460198],
       [ 0.05709085, -0.54808987,  0.74620428, -1.50378408],
       [ 0.83158447, -0.38481785, -1.13312624,  0.40238384],
       [ 0.16265428,  1.07551965,  1.00572247, -1.082648  ]])

In [21]:
np.random.randint(1,10)

4

In [22]:
np.random.randint(1,10)

9

In [23]:
np.random.randint(1,20,5)

array([13,  4, 15,  2, 14])

In [24]:
benimdizim = np.arange(20)

In [25]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
benimrandom = np.random.randint(0,100,20)

In [41]:
benimrandom

array([68, 50, 50, 79, 59, 96,  3, 38, 82, 51, 92, 79, 25, 89, 64, 92,  6,
       47,  3,  8])

# numpy dizi methodları


In [42]:
benimdizim.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
benimdizim.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [44]:
benimdizim.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
benimdizim.max()

19

In [46]:
benimrandom.max()

96

In [47]:
benimrandom.min()

3

In [48]:
benimrandom.argmax()

5

In [49]:
benimrandom.argmin()

6

In [50]:
benimrandom

array([68, 50, 50, 79, 59, 96,  3, 38, 82, 51, 92, 79, 25, 89, 64, 92,  6,
       47,  3,  8])

In [51]:
benimdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
reshapedizim = benimdizim.reshape(10,2)

In [53]:
reshapedizim

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])